### ISSUE TITLE
create_bucket error for region eu-central-1 

### ISSUE THREAD

**Issue by Hrabal** [kennethreitz/bucketstore#18]
related to the issue https://github.com/boto/boto3/issues/781
if .aws/config file contains `region=eu-central-1` this code will trow an exception:

```
>>> import bucketstore
>>> bucket = bucketstore.get('foobucket', create=True)                                                       
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bucketstore.py", line 13, in get
    return S3Bucket(bucket_name, create=create)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bucketstore.py", line 35, in __init__
    self._boto_s3.create_bucket(Bucket=self.name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/Users/federicocerchiari/Library/Python/3.6/lib/python/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/federicocerchiari/Library/Python/3.6/lib/python/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.
```

For what I understand this is due to how boto3 manages regions, if I remove the .aws/config file then the code above will run properly, creating a bucket in the US East region.

This makes impossible using bucketstore with a custom region.

In the boto3 issue a workaround is proposed, that is to provide the `CreateBucketConfiguration={'LocationConstraint': 'my desired region'}` parameter in the `create_bucket` call, but this will fail if the .aws/config file contains a region different from US East.

Edit:
I hacked the workaround above like this:
```
def get(bucket_name, create=False, region=None):
    return S3Bucket(bucket_name, create=create, region=None)

...
class S3Bucket(object):
    """An Amazon S3 Bucket."""

    def __init__(self, name, create=False, region=None):
...
            if create:
                # Create the bucket.
                extra_kwargs = {}
                if region:
                    extra_kwargs.update({'CreateBucketConfiguration': {'LocationConstraint': region}})
                self._boto_s3.create_bucket(Bucket=self.name, **extra_kwargs)
....
```

then called
```
bucket = bucketstore.get('fooobucket', create=True, region='eu-central-1')
```

and the result is no exception raised but the bucket is been created in the US East region. So this workaround is not working properly.

**Comment by ParthS007** [comment]
Closing this due to inactivity :+1:

**Comment by nayrb-n** [comment]
.
